accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import user_signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", user_signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
    AccountListView,
    AccountCreateView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("categories/", ExpenseCategoryListView.as_view(), name="list_categories"),
    path("accounts/", AccountListView.as_view(), name="accounts_list"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(), name="create_category"),
    path("accounts/create/", AccountCreateView.as_view(), name="create_account"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models

# Create your models here.

from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(USER_MODEL, related_name="categories", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(USER_MODEL, related_name="accounts", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(USER_MODEL, related_name="receipts", on_delete=models.CASCADE)
    category = models.ForeignKey(ExpenseCategory, related_name="receipts", on_delete=models.CASCADE)
    account = models.ForeignKey(Account, related_name="receipts", on_delete=models.CASCADE, null=True)

accounts/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate


def user_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {'form': form})

receipts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

# Create your views here.

from receipts.models import Receipt, Account, ExpenseCategory
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/receipt_list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/receipt_new.html"
    fields = [
        'vendor',
        'total',
        'tax',
        'date',
        'category',
        'account',
    ]

    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.purchaser = self.request.user
        return super().form_valid(form)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/category_list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/category_new.html"
    fields = ['name']
    success_url = reverse_lazy("list_categories")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/account_list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/account_new.html"
    fields = ['name', 'number']
    success_url = reverse_lazy("accounts_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Expenses</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li>
          <a href="{% url 'home' %}">Expenses</a>
        </li>
        {% comment %} <li>
          <a href="{% url 'tags_list' %}">Tags</a>
        </li>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'mealplans_list' %}">Meal Plans</a>
        </li>
        <li>
          <a href="{% url 'shopping_list' %}">Shop List &#40;{{ total_item_shop }}&#41;</a>
        </li>
        {% endif %}
        {% if user.is_staff %}
        <li>
          <a href="{% url 'admin:index' %}">Admin</a>
        </li>
        {% endif %} {% endcomment %}
        {% if not user.is_authenticated %}
        <li>
          <a href="{% url 'login' %}">Login</a>
        </li>
        <li>
            <a href="{% url 'signup' %}">Sign Up</a>
        </li>
        {% endif %}
        {% comment %} <li>
          <a href="{% url 'recipe_new' %}">Write a recipe</a>
        </li> {% endcomment %}
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'create_receipt' %}">Create a Receipt</a>
        </li>
        <li>
            <a href="{% url 'list_categories' %}">Categories</a>
        </li>
        <li>
            <a href="{% url 'create_category' %}">Create a Category</a>
        </li>
        <li>
            <a href="{% url 'accounts_list' %}">Accounts</a>
        </li>
        <li>
            <a href="{% url 'create_account' %}">Create an Account</a>
        </li>
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% block pagination %}
    {% endblock pagination %}
  </header>

  {% block content %}
  {% endblock content %}
</body>

</html>

receipts/templates/receipts/account_list.html
{% extends 'base.html' %}


{% block content %}
    <main>
        <h1>My Accounts</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Number of receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for acc in account_list %}
                    <tr>
                        <td>{{acc}}</td>
                        <td>{{acc.number}}</td>
                        <td>{{acc.receipts.all | length}}</td>
                    </tr>
                {% endfor %}
            </tbody>
    </main>
{% endblock content %}

receipts/templates/receipts/account_new.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Account</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
            <button class="button">Create</button>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/category_list.html
{% extends 'base.html' %}


{% block content %}
    <main>
        <h1>My Categories</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for category in expensecategory_list %}
                    <tr>
                        <td>{{category}}</td>
                        <td>{{category.receipts.all | length}}</td>
                    </tr>
                {% endfor %}
            </tbody>
    </main>
{% endblock content %}

receipts/templates/receipts/category_new.html
{% extends 'base.html' %}


{% block content %}
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
            <button class="button">Create</button>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/receipt_list.html
{% extends 'base.html' %}


{% block content %}
    <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for receipt in receipt_list %}
                    <tr>
                        <td>{{receipt.vendor}}</td>
                        <td>{{receipt.total}}</td>
                        <td>{{receipt.tax}}</td>
                        <td>{{receipt.date|date:"m-d-Y"}}</td>
                        <td>{{receipt.category}}</td>
                        <td>{{receipt.account}}</td>
                    </tr>
                {% endfor %}
            </tbody>
    </main>
{% endblock content %}

receipts/templates/receipts/receipt_new.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
            <button class="button">Create</button>
        </div>
    </main>
{% endblock content %}